// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/transport/grpc/proto/visit_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/lyft/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cebbc4cae06061be, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type VisitRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitRequest) Reset()         { *m = VisitRequest{} }
func (m *VisitRequest) String() string { return proto.CompactTextString(m) }
func (*VisitRequest) ProtoMessage()    {}
func (*VisitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cebbc4cae06061be, []int{1}
}

func (m *VisitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitRequest.Unmarshal(m, b)
}
func (m *VisitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitRequest.Marshal(b, m, deterministic)
}
func (m *VisitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitRequest.Merge(m, src)
}
func (m *VisitRequest) XXX_Size() int {
	return xxx_messageInfo_VisitRequest.Size(m)
}
func (m *VisitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VisitRequest proto.InternalMessageInfo

func (m *VisitRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VisitRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *VisitRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type VisitResponse struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VisitResponse) Reset()         { *m = VisitResponse{} }
func (m *VisitResponse) String() string { return proto.CompactTextString(m) }
func (*VisitResponse) ProtoMessage()    {}
func (*VisitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cebbc4cae06061be, []int{2}
}

func (m *VisitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitResponse.Unmarshal(m, b)
}
func (m *VisitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitResponse.Marshal(b, m, deterministic)
}
func (m *VisitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitResponse.Merge(m, src)
}
func (m *VisitResponse) XXX_Size() int {
	return xxx_messageInfo_VisitResponse.Size(m)
}
func (m *VisitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VisitResponse proto.InternalMessageInfo

func (m *VisitResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VisitResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *VisitResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *VisitResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *VisitResponse) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "pb.ID")
	proto.RegisterType((*VisitRequest)(nil), "pb.VisitRequest")
	proto.RegisterType((*VisitResponse)(nil), "pb.VisitResponse")
}

func init() {
	proto.RegisterFile("src/transport/grpc/proto/visit_service.proto", fileDescriptor_cebbc4cae06061be)
}

var fileDescriptor_cebbc4cae06061be = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0xc7, 0xcd, 0xe4, 0x7a, 0x31, 0xa3, 0xb7, 0xd4, 0x59, 0x48, 0x8d, 0x1f, 0xb7, 0x04, 0x91,
	0x50, 0x6c, 0x06, 0xeb, 0xc6, 0x8f, 0x55, 0xa5, 0x20, 0xdd, 0x88, 0xa4, 0xe2, 0xc2, 0x4d, 0x99,
	0x24, 0xd3, 0x38, 0x90, 0x64, 0xc6, 0x99, 0x93, 0x80, 0x14, 0x37, 0xbe, 0x82, 0x3b, 0x1f, 0xc5,
	0x95, 0xaf, 0x20, 0xbe, 0x82, 0x1b, 0xdf, 0x42, 0xf2, 0x65, 0x5b, 0x2b, 0xde, 0x55, 0x3e, 0xce,
	0xef, 0xff, 0xff, 0xcf, 0x9c, 0x73, 0xf0, 0x03, 0xa3, 0x63, 0x0a, 0x9a, 0x15, 0x46, 0x49, 0x0d,
	0x34, 0xd5, 0x2a, 0xa6, 0x4a, 0x4b, 0x90, 0xb4, 0x12, 0x46, 0xc0, 0xda, 0x70, 0x5d, 0x89, 0x98,
	0x07, 0xcd, 0x3f, 0x82, 0x54, 0xe4, 0x9e, 0xa7, 0x52, 0xa6, 0x19, 0x6f, 0xa9, 0xa8, 0xdc, 0x50,
	0x10, 0x39, 0x37, 0xc0, 0x72, 0xd5, 0x42, 0xee, 0xed, 0x0e, 0x60, 0x4a, 0x50, 0x56, 0x14, 0x12,
	0x18, 0x08, 0x59, 0x98, 0xae, 0xfa, 0x2c, 0x15, 0xf0, 0xae, 0x8c, 0x82, 0x58, 0xe6, 0x34, 0xfb,
	0xb0, 0x81, 0xd6, 0x27, 0x9e, 0xa6, 0xbc, 0x98, 0x56, 0x2c, 0x13, 0x09, 0x03, 0x4e, 0x8f, 0x5e,
	0x5a, 0xb1, 0x77, 0x8e, 0xd1, 0x72, 0x41, 0x6e, 0x62, 0x24, 0x92, 0x91, 0x35, 0xb6, 0xfc, 0xb3,
	0xe7, 0xce, 0xd7, 0x5f, 0xdf, 0xec, 0x93, 0x09, 0xf2, 0x2f, 0x85, 0x48, 0x24, 0xde, 0x16, 0x5f,
	0x7b, 0x53, 0x9f, 0x3b, 0xe4, 0xef, 0x4b, 0x6e, 0xe0, 0x3f, 0x28, 0xf1, 0x31, 0xde, 0x08, 0x6d,
	0x60, 0x5d, 0xb0, 0x9c, 0x8f, 0xd0, 0xd8, 0xf2, 0x9d, 0x0e, 0xd1, 0x68, 0x88, 0x42, 0xa7, 0x29,
	0xbe, 0x64, 0x39, 0x27, 0xf7, 0xb1, 0x93, 0xb1, 0x1e, 0xb4, 0xff, 0x06, 0xaf, 0xd4, 0xb5, 0x9a,
	0xf3, 0xbe, 0x5b, 0xf8, 0xac, 0x4b, 0x37, 0x4a, 0x16, 0x86, 0x93, 0xc1, 0x2e, 0xbe, 0xc9, 0xbc,
	0x73, 0x9c, 0xb9, 0x1f, 0x74, 0xeb, 0x28, 0x68, 0xe7, 0x4e, 0x9e, 0x60, 0x1c, 0x6b, 0xce, 0x80,
	0x27, 0x6b, 0x06, 0xa3, 0x93, 0xb1, 0xe5, 0x5f, 0x9d, 0xb9, 0x41, 0xdb, 0xeb, 0xa0, 0x1f, 0x46,
	0xf0, 0xba, 0x1f, 0x46, 0xe8, 0x74, 0xf4, 0x1c, 0x6a, 0x69, 0xa9, 0x92, 0x5e, 0x7a, 0xf9, 0x62,
	0x69, 0x47, 0xcf, 0x61, 0xf6, 0xc5, 0xea, 0x3a, 0xba, 0x6a, 0x17, 0x81, 0x3c, 0xc6, 0xf6, 0x0b,
	0x0e, 0xe4, 0x34, 0x50, 0x51, 0xb0, 0x5c, 0xb8, 0xd7, 0xeb, 0xe7, 0xc1, 0xa5, 0xbd, 0x1b, 0x9f,
	0x7e, 0xfc, 0xfc, 0x8c, 0x86, 0x64, 0x40, 0xab, 0x87, 0xed, 0x16, 0xd1, 0xad, 0x48, 0x3e, 0x92,
	0x57, 0xd8, 0x5e, 0x71, 0x20, 0xc3, 0x3d, 0x45, 0x33, 0xa4, 0x7f, 0x79, 0xdc, 0x6b, 0x3c, 0xee,
	0x7a, 0xce, 0x1f, 0x8f, 0xa7, 0xd6, 0xe4, 0xed, 0xc0, 0x3d, 0xf8, 0x8e, 0x4e, 0x9b, 0xb3, 0x3f,
	0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x11, 0xec, 0xff, 0xb2, 0xc5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VisitServiceClient is the client API for VisitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisitServiceClient interface {
	// Simple return the visit id
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VisitResponse, error)
	// Update/Create a device
	Set(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error)
}

type visitServiceClient struct {
	cc *grpc.ClientConn
}

func NewVisitServiceClient(cc *grpc.ClientConn) VisitServiceClient {
	return &visitServiceClient{cc}
}

func (c *visitServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*VisitResponse, error) {
	out := new(VisitResponse)
	err := c.cc.Invoke(ctx, "/pb.VisitService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitServiceClient) Set(ctx context.Context, in *VisitRequest, opts ...grpc.CallOption) (*VisitResponse, error) {
	out := new(VisitResponse)
	err := c.cc.Invoke(ctx, "/pb.VisitService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitServiceServer is the server API for VisitService service.
type VisitServiceServer interface {
	// Simple return the visit id
	Get(context.Context, *ID) (*VisitResponse, error)
	// Update/Create a device
	Set(context.Context, *VisitRequest) (*VisitResponse, error)
}

func RegisterVisitServiceServer(s *grpc.Server, srv VisitServiceServer) {
	s.RegisterService(&_VisitService_serviceDesc, srv)
}

func _VisitService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).Set(ctx, req.(*VisitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VisitService",
	HandlerType: (*VisitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VisitService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _VisitService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/transport/grpc/proto/visit_service.proto",
}
