// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: src/transport/grpc/proto/visit.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on VisitRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *VisitRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetID() < 0 {
		return VisitRequestValidationError{
			field:  "ID",
			reason: "value must be greater than or equal to 0",
		}
	}

	if utf8.RuneCountInString(m.GetFirstName()) < 2 {
		return VisitRequestValidationError{
			field:  "FirstName",
			reason: "value length must be at least 2 runes",
		}
	}

	if utf8.RuneCountInString(m.GetLastName()) < 2 {
		return VisitRequestValidationError{
			field:  "LastName",
			reason: "value length must be at least 2 runes",
		}
	}

	return nil
}

// VisitRequestValidationError is the validation error returned by
// VisitRequest.Validate if the designated constraints aren't met.
type VisitRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VisitRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VisitRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VisitRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VisitRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VisitRequestValidationError) ErrorName() string { return "VisitRequestValidationError" }

// Error satisfies the builtin error interface
func (e VisitRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVisitRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VisitRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VisitRequestValidationError{}

// Validate checks the field values on VisitResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *VisitResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for ID

	// no validation rules for FirstName

	// no validation rules for LastName

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VisitResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VisitResponseValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// VisitResponseValidationError is the validation error returned by
// VisitResponse.Validate if the designated constraints aren't met.
type VisitResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VisitResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VisitResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VisitResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VisitResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VisitResponseValidationError) ErrorName() string { return "VisitResponseValidationError" }

// Error satisfies the builtin error interface
func (e VisitResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVisitResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VisitResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VisitResponseValidationError{}
