// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: src/app/proto/visit_service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on ID with the rules defined in the proto
// definition for this message. If any rules are violated, an error is returned.
func (m *ID) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetId() < 2 {
		return IDValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 2",
		}
	}

	return nil
}

// IDValidationError is the validation error returned by ID.Validate if the
// designated constraints aren't met.
type IDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IDValidationError) ErrorName() string { return "IDValidationError" }

// Error satisfies the builtin error interface
func (e IDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IDValidationError{}

// Validate checks the field values on Visit with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Visit) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetId() < 2 {
		return VisitValidationError{
			field:  "Id",
			reason: "value must be greater than or equal to 2",
		}
	}

	if utf8.RuneCountInString(m.GetFirstName()) < 2 {
		return VisitValidationError{
			field:  "FirstName",
			reason: "value length must be at least 2 runes",
		}
	}

	if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return VisitValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// VisitValidationError is the validation error returned by Visit.Validate if
// the designated constraints aren't met.
type VisitValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VisitValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VisitValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VisitValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VisitValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VisitValidationError) ErrorName() string { return "VisitValidationError" }

// Error satisfies the builtin error interface
func (e VisitValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVisit.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VisitValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VisitValidationError{}
