// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/app/proto/visit_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ID struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb667a08f2917e3b, []int{0}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Visit struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string               `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Visit) Reset()         { *m = Visit{} }
func (m *Visit) String() string { return proto.CompactTextString(m) }
func (*Visit) ProtoMessage()    {}
func (*Visit) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb667a08f2917e3b, []int{1}
}

func (m *Visit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visit.Unmarshal(m, b)
}
func (m *Visit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visit.Marshal(b, m, deterministic)
}
func (m *Visit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visit.Merge(m, src)
}
func (m *Visit) XXX_Size() int {
	return xxx_messageInfo_Visit.Size(m)
}
func (m *Visit) XXX_DiscardUnknown() {
	xxx_messageInfo_Visit.DiscardUnknown(m)
}

var xxx_messageInfo_Visit proto.InternalMessageInfo

func (m *Visit) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Visit) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Visit) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*ID)(nil), "pb.ID")
	proto.RegisterType((*Visit)(nil), "pb.Visit")
}

func init() { proto.RegisterFile("src/app/proto/visit_service.proto", fileDescriptor_cb667a08f2917e3b) }

var fileDescriptor_cb667a08f2917e3b = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0xd7, 0x8c, 0x0d, 0x1a, 0x65, 0x8c, 0x1c, 0xc6, 0x28, 0x93, 0xcd, 0x81, 0xb0, 0xcb,
	0x12, 0x9d, 0x20, 0x78, 0x54, 0x06, 0xb2, 0x8b, 0x87, 0x4d, 0xbc, 0x96, 0xb4, 0xcd, 0xea, 0x87,
	0x6b, 0x13, 0x9a, 0x6f, 0x1d, 0x22, 0x5e, 0x7c, 0x05, 0x1f, 0xcd, 0x07, 0x10, 0xc4, 0x07, 0x91,
	0x35, 0x9b, 0xf3, 0x94, 0x90, 0xdf, 0xef, 0xcf, 0x97, 0xff, 0x47, 0x4f, 0x6d, 0x11, 0x0b, 0x69,
	0x8c, 0x30, 0x85, 0x46, 0x2d, 0x4a, 0xb0, 0x80, 0xa1, 0x55, 0x45, 0x09, 0xb1, 0xe2, 0xd5, 0x1b,
	0x23, 0x26, 0x0a, 0xfa, 0xa9, 0xd6, 0xe9, 0x4a, 0x39, 0x2b, 0x5a, 0x2f, 0x05, 0x42, 0xa6, 0x2c,
	0xca, 0xcc, 0x38, 0x29, 0xe8, 0xed, 0x04, 0x69, 0x40, 0xc8, 0x3c, 0xd7, 0x28, 0x11, 0x74, 0x6e,
	0x77, 0xf4, 0x2a, 0x05, 0x7c, 0x5a, 0x47, 0x3c, 0xd6, 0x99, 0xc8, 0x36, 0x80, 0xcf, 0x7a, 0x23,
	0x52, 0x3d, 0xae, 0xe0, 0xb8, 0x94, 0x2b, 0x48, 0x24, 0xea, 0xc2, 0x8a, 0xbf, 0xab, 0xcb, 0x0d,
	0x7b, 0x94, 0xcc, 0xa6, 0xac, 0x43, 0x09, 0x24, 0x5d, 0x6f, 0xe0, 0x8d, 0x1a, 0xb7, 0xcd, 0xef,
	0xaf, 0x3e, 0x69, 0xd7, 0xe6, 0x04, 0x92, 0xe1, 0x0b, 0x6d, 0x3c, 0x6e, 0xff, 0xcb, 0x5a, 0x07,
	0x61, 0x0b, 0xd8, 0x19, 0xa5, 0x4b, 0x28, 0x2c, 0x86, 0xb9, 0xcc, 0x54, 0x97, 0x0c, 0xbc, 0x91,
	0xef, 0x82, 0x86, 0xcc, 0xfd, 0x8a, 0xdc, 0xcb, 0x4c, 0xb1, 0x6b, 0x4a, 0xe3, 0x42, 0x49, 0x54,
	0x49, 0x28, 0xb1, 0x5b, 0x1f, 0x78, 0xa3, 0xa3, 0x49, 0xc0, 0x5d, 0x11, 0xbe, 0x6f, 0xca, 0x1f,
	0xf6, 0x4d, 0xe7, 0xfe, 0xce, 0xbe, 0xc1, 0x49, 0x48, 0x8f, 0xab, 0xd1, 0x0b, 0xb7, 0x29, 0x76,
	0x4e, 0xeb, 0x77, 0x0a, 0x59, 0x93, 0x9b, 0x88, 0xcf, 0xa6, 0x81, 0xbf, 0x3d, 0x2b, 0x61, 0xd8,
	0x79, 0xff, 0xfc, 0xf9, 0x20, 0x6d, 0xd6, 0x12, 0xe5, 0x85, 0x5b, 0xaf, 0x78, 0x85, 0xe4, 0x8d,
	0x9d, 0xd0, 0xfa, 0x42, 0x21, 0x3b, 0x98, 0xff, 0x43, 0xb5, 0xa8, 0x59, 0xcd, 0xbf, 0xfc, 0x0d,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x6a, 0x22, 0x87, 0xa0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VisitServiceClient is the client API for VisitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VisitServiceClient interface {
	// Simple return the visit id
	Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Visit, error)
	// Update/Create a device
	Set(ctx context.Context, in *Visit, opts ...grpc.CallOption) (*Visit, error)
}

type visitServiceClient struct {
	cc *grpc.ClientConn
}

func NewVisitServiceClient(cc *grpc.ClientConn) VisitServiceClient {
	return &visitServiceClient{cc}
}

func (c *visitServiceClient) Get(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Visit, error) {
	out := new(Visit)
	err := c.cc.Invoke(ctx, "/pb.VisitService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visitServiceClient) Set(ctx context.Context, in *Visit, opts ...grpc.CallOption) (*Visit, error) {
	out := new(Visit)
	err := c.cc.Invoke(ctx, "/pb.VisitService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisitServiceServer is the server API for VisitService service.
type VisitServiceServer interface {
	// Simple return the visit id
	Get(context.Context, *ID) (*Visit, error)
	// Update/Create a device
	Set(context.Context, *Visit) (*Visit, error)
}

func RegisterVisitServiceServer(s *grpc.Server, srv VisitServiceServer) {
	s.RegisterService(&_VisitService_serviceDesc, srv)
}

func _VisitService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).Get(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisitService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Visit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisitServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VisitService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisitServiceServer).Set(ctx, req.(*Visit))
	}
	return interceptor(ctx, in, info, handler)
}

var _VisitService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VisitService",
	HandlerType: (*VisitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VisitService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _VisitService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/app/proto/visit_service.proto",
}
